"""koliko

Revision ID: 681574d328f7
Revises: 850187cb2b6e
Create Date: 2024-08-26 09:59:29.442622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681574d328f7'
down_revision = '850187cb2b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('atelier_id', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=False),
    sa.Column('mois', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['atelier_id'], ['atelier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depense')
    # ### end Alembic commands ###
