"""lil

Revision ID: 850187cb2b6e
Revises: 166a3d4a8c9a
Create Date: 2024-08-19 14:28:58.582785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '850187cb2b6e'
down_revision = '166a3d4a8c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mois')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mois',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('libelle', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('travail', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
