"""ok

Revision ID: 92dcbef7b071
Revises: 
Create Date: 2024-08-13 09:19:14.960788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92dcbef7b071'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mois', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atelier_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'atelier', ['atelier_id'], ['id'])

    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mois_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'mois', ['mois_id'], ['id'])
        batch_op.drop_column('mois')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mois', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mois_id')

    with op.batch_alter_table('mois', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travail', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vente', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('libelle', ['libelle'], unique=True)
        batch_op.drop_column('atelier_id')
        batch_op.drop_column('Vente')
        batch_op.drop_column('Travail')

    # ### end Alembic commands ###
