"""o

Revision ID: a8a733924177
Revises: 92dcbef7b071
Create Date: 2024-08-13 10:57:43.805965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8a733924177'
down_revision = '92dcbef7b071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mois', schema=None) as batch_op:
        batch_op.alter_column('travail',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('vente',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_index('libelle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mois', schema=None) as batch_op:
        batch_op.create_index('libelle', ['libelle'], unique=True)
        batch_op.alter_column('vente',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('travail',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
