"""oky

Revision ID: beb1fd3f3aea
Revises: a8a733924177
Create Date: 2024-08-16 16:52:34.424763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beb1fd3f3aea'
down_revision = 'a8a733924177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mois', schema=None) as batch_op:
        batch_op.drop_constraint('mois_ibfk_1', type_='foreignkey')
        batch_op.drop_column('atelier_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mois', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atelier_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('mois_ibfk_1', 'atelier', ['atelier_id'], ['id'])

    # ### end Alembic commands ###
